### ISSUE TITLE
Pipework in AWS?

### ISSUE THREAD

**Issue by jaychris** [jpetazzo/pipework#169]
We've been using Pipework to great effect on our LAN, to provision container interfaces that configured addresses via the LAN DHCP server.  Works well, no issues, etc...

Same setup in an AWS VPC, the interface (eth1) is configured via pipework, but never receives a response via DHCP.  I can see the request going out on the VPC network, using tcpdump.

Just wondering if you've tried pipework in AWS successfully.  I did some searching to see if there is something that needs to be done to get a response from the AWS VPC DHCP server (certain MAC range or something), but nothing so far.

EDIT:  My unconfirmed (so  far) suspicion is that AWS uses some sort of network registry to limit the MAC addresses of interfaces it will assign IP's to or allow in the VPC.  Can't find any information in those regards, but I'm trying to test it out.

**Comment by jpetazzo** [comment]
You are right—AFAIK, AWS VPC cannot have arbitrary MAC addresses. So you have multiple options:

- use ENI and move a whole ENI to a container (but that'll only work for a small amount of containers per machine, since you'll dedicate an ENI to the container)
- if you only need intercontainer communication, use some kind of overlay network

Sorry!
