### ISSUE TITLE
pipework does not work on Centos 6.5 (Object "netns" is unknown, try "ip help".)

### ISSUE THREAD

**Issue by tlvu** [jpetazzo/pipework#180]
I run pipework this way: `sudo sh -x ./pipework eth0 containerid dhclient` and have the following output

```
 + case "$IPADDR" in
 + DHCP_CLIENT=dhclient
 + installed dhclient
 + command -v dhclient
 + '[' dhclient ']'
 + case "$IPADDR" in
 + '[' 20740 ']'
 + NSPID=20740
 + '[' phys = phys ']'
 + '[' '' ']'
 + '[' '!' -d /var/run/netns ']'
 + mkdir -p /var/run/netns
 + rm -f /var/run/netns/20740
 + ln -s /proc/20740/ns/net /var/run/netns/20740
 + '[' phys = bridge ']'
 ++ ip link show eth0
 ++ awk '{print $5}'
 + MTU=1500
 + '[' phys = bridge ']'
 + '[' phys = phys ']'
 + '[' '' ']'
 + GUEST_IFNAME=ph20740eth1
 + ip link add link eth0 dev ph20740eth1 mtu 1500 type macvlan mode bridge
 + ip link set eth0 up
 + '[' phys = ipoib ']'
 + ip link set ph20740eth1 netns 20740
 + ip netns exec 20740 ip link set ph20740eth1 name eth1
 Object "netns" is unknown, try "ip help".
```

Searching the internet, it seems I need a new iproute package from http://rdo.fedorapeople.org/rdo-release.rpm so I installed that package which gives me a new yum repo pointing to https://repos.fedorapeople.org/repos/openstack/openstack-kilo/.

However there is no "el6" there so now I am stuck.

**Comment by jpetazzo** [comment]
Yes, you need a newer `iproute` package, unfortunately. I'm leaving this issue open, because this might be addressed in a future version of pipework; but for now, you have to find an upgraded `iproute`. I don't use CentOS so I have no idea what are the appropriate channels for that; worst case scenario you could just download the source for a recent iproute and compile it (it should have pretty minimal dependencies).
