### ISSUE TITLE
Pipework and after reboot

### ISSUE THREAD

**Issue by remotesyssupport** [jpetazzo/pipework#6]
After the host server reboots, the docker containers running previous will be brought up, but these come without the pipework networking previous placed or the IPs assigned via pipework..

Would like to know of the ways to keep the mapping [docker-containers to pipework assigned IPs] and the same be brought up after reboot. 

In certain scenarios, the docker container would change [meaning some of the containers retired and new ones added].

Thanks of any suggestion in this regards.....

**Comment by dreamcat4** [comment]
Hello.
Have now been working on making a docker image for pipework. My wrapper script around pipework (`entry point.sh`) will be smart enough to listen for affected containers on your host system. And auto-cun the relevant pipework cmd(s) if needed.

Configuration is on ENV vars on your affected app/service containers e.g. `docker run -e pipework_cmd=….`. The idea is you write that pipework configuration in your orchestration `.yml` configuration file.

This new docker image should in theory be compatible with any docker orchestration service. However ATM it's only being tested on `crane`. Because `fig` does not yet have the necessary new configuration flag `pid: host`, which is required. As pipework needs new host pid namespace option in Docker 1.5.0. I don't use know about or use kubernetes but probably the same situation.

CoreOS might work - but only if your coreOS host system implements the necessary host-side networking tools for pipework script.

Still in testing / development.

**Comment by dreamcat4** [comment]
Update:

`pipework` docker image is now publicly released as `dreamcat4/pipework` on dockerhub. It requires docker 1.5.0 to work.

You can specify all of your pipework config (ip addresses etc.) within you orchestration tool's `.yml` file. Like this:

https://github.com/dreamcat4/docker-images/blob/master/pipework/3.%20Examples.md#crane-recommended

It listens as a daemon. OR you can run the pipework container from the command line. Just like the conventional pipework host script. Which is good too, for quickly testing / trying things out.

**Comment by jpetazzo** [comment]
After lots of thoughts (and some discussion with @dreamcat4), I have added a paragraph in the README to explain that if people wanted integration with other tools (including automatically setting up pipework etc), they could use [dreamcat4/pipework](https://registry.hub.docker.com/u/dreamcat4/pipework/) and a short explanation of how it works.

Thanks a lot for providing this; it's incredibly powerful! And in the spirit of pipework itself, it's very easy to understand how it works, how to customize it, and how to build on top of it.

👍
